//
// Created by Vladislav Molodtsov on 2019-03-31.
//

#ifndef __CHANNELS_H__
#define __CHANNELS_H__

#define FROM_COMMUNICATION_TO_STRATEGY 1
#define FROM_STRATEGY_TO_COMMUNICATION 2

#define FROM_MOVEMENT_TO_STRATEGY 3
#define FROM_STRATEGY_TO_MOVEMENT 4

#define FROM_STRATEGY_TO_VISION 5
#define FROM_VISION_TO_STRATEGY 6

#define FROM_STRATEGY_TO_LOCALIZATION 7
#define FROM_LOCALIZATION_TO_STRATEGY 8

#define FROM_VISION_TO_LOCALIZATION 9
#define FROM_LOCALIZATION_TO_VISION 10

#endif /* __CHANNELS_H__ */
